### PR TITLE
support workflowsets in add_candidates

### LINKED ISSUE #57: support workflowsets package
Once [`workflowsets`](https://github.com/tidymodels/workflowsets) is on CRAN, `stacks` ought to support it. I think the approach that makes the most sense here is making `add_candidates()` a generic and introducing an `add_candidates.workflow_set` method. :-)

### PR DESCRIPTION
**Pull request by simonpcouch**
PRing for checks. Closes #57.🌼

### CODE REVIEW

**Comment by simonpcouch** [comment]
There’s one issue that I’m having trouble debugging here. The [`workflow_map` code](https://github.com/tidymodels/stacks/pull/65/commits/844048ef706ca7dd8097c4698fd661eecb39ddcb#diff-7668f2941ac5efb18f4f2164b1f839a68738c36eef4b7f8a59d15ad3dc8c1bd2R230-R251) in `man-roxygen/example_models.Rmd` seems to result in 8 preprocessors for the spline model, but results in 9 when ran with a typical `tune` workflow. I’m assuming there’s some element of the `workflowsets` pipeline that I’m not picking up on.

**Comment by topepo** [comment]
Maybe try with the latest `workflowsets` (I just sent it to CRAN). I get three workflows: 

```
> reg_wf_map
# A workflow set/tibble: 3 x 4
  wflow_id      info             option    result   
  <chr>         <list>           <list>    <list>   
1 lr_lr         <tibble [1 × 4]> <opts[3]> <rsmp[+]>
2 svm_svm       <tibble [1 × 4]> <opts[3]> <tune[+]>
3 spline_spline <tibble [1 × 4]> <opts[3]> <tune[+]>
```

**Comment by topepo** [comment]
I'll make some modifications to this PR for racing methods.

**Comment by simonpcouch** [comment]
Sounds great, much appreciated!

**Comment by topepo** [comment]
I think that we should move the cross-package unit tests to `extratests`. We could create the workflow set (and racing objects) there and not have to worry about object size or testing time. Is that okay?

**Comment by simonpcouch** [comment]
All for it!

**Comment by topepo** [comment]
I think that it's ready to merge 🎈

**Review by topepo — APPROVED** [review]

**Comment by simonpcouch** [comment]
Nice! Will take a more thorough look tomorrow or Friday.

**Comment by simonpcouch** [comment]
Yup, whatever that mismatch was that I was seeing was resolved in the last couple weeks. Loving the `collate_predictions` addition here. Will merge after checks pass!

**Pull request merged**
